### ISSUE TITLE
New-GPPGroup -DeleteAllUsers or -DeleteAllGroups parameters do not work

### ISSUE THREAD

**Issue by Borgquite** [exchange12rocks/PSGPPreferences#26]
Love the module but when trying to use New-GPPGroup with -DeleteAllUsers or -DeleteAllGroups the parameters have no effect.

To replicate, just run:
`New-GPPGroup -GPOName "TEST GPO" -Update -Name "Administrators" -DeleteAllUsers -DeleteAllGroups`

The resultant Group Policy will have 'Delete all member users' and 'Delete all member groups' set to Disabled

**Comment by exchange12rocks** [comment]
Thank you Chris! I will deal with it soon, hopefully on this weekend

**Comment by exchange12rocks** [comment]
Could you please check out the [dev](https://github.com/exchange12rocks/PSGPPreferences/tree/dev) branch?

**Comment by Borgquite** [comment]
Yep, dev branch works now :)
