### ISSUE TITLE
Set-GPPGroup -DeleteAllUsers or -DeleteAllGroups parameters produce error when policy contains multiple groups

### ISSUE THREAD

**Issue by Borgquite** [exchange12rocks/PSGPPreferences#27]
Consider this scenario:

```
New-GPPGroup -GPOName "TEST GPO" -Update -Name "Administrators"
Set-GPPGroup -GPOName "TEST GPO" -Name "Administrators" -DeleteAllUsers -DeleteAllGroups
New-GPPGroup -GPOName "TEST GPO" -Update -Name "Remote Desktop Users"
Set-GPPGroup -GPOName "TEST GPO" -Name "Remote Desktop Users" -DeleteAllUsers -DeleteAllGroups
```

The 'Administrators' group will be created correctly with Delete all users and Delete all groups set

The 'Remote Desktop Users' group will be created **twice**, and the second command will error out:

```
Exception calling "Remove" with "1" argument(s): "Collection was of a fixed size."
At C:\Program Files\WindowsPowerShell\Modules\PSGPPreferences\0.2.0\Groups\Remove-GPPGroupsItem.ps1:117 char:21
+                     [void]$WorkObjects.Remove($ObjectToRemove)
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException
```

Seems that Set-GPPGroup can't handle multiple groups in a single policy

**Comment by exchange12rocks** [comment]
Thanks you Chris! Appreciate your bug reports!

**Comment by exchange12rocks** [comment]
Could you please check out the [dev](https://github.com/exchange12rocks/PSGPPreferences/tree/dev) branch?

**Comment by Borgquite** [comment]
Hey, just tested, that seems to be working fine.

Thanks for the swift reply! This module shows a lot of promise, please do keep developing! I'll post a few more bugs in a minute.
