### ISSUE TITLE
Can't retrieve values of DeleteAllUsers or DeleteAllGroups once set on a group

### ISSUE THREAD

**Issue by Borgquite** [exchange12rocks/PSGPPreferences#30]
Hey,

A few more small ones which are really helpful for my current use case:

I can't find a way to retrieve the value of DeleteAllUsers or DeleteAllGroups from Get-GPPGroup - please could this be added?

```
PS C:\Windows\system32> New-GPPGroup -GPOName "TEST GPO" -Update -Name "Administrators" -DeleteAllUsers -DeleteAllGroups

PS C:\Windows\system32> Get-GPPGroup -GPOName "TEST GPO" -Name "Administrators"


Properties   : GPPItemPropertiesGroup
name         : Administrators
changed      : 04/04/2022 11:25:45
uid          : <redacted>
removePolicy : False
bypassErrors : True
disabled     : False
Filters      : 
```

**Comment by exchange12rocks** [comment]
That's because those are set at the `Properties` property of a group item object:
`(Get-GPPGroup -GPOName "TEST GPO" -Name "Administrators").Properties`

**Comment by Borgquite** [comment]
Ah :) Thanks!
