### ISSUE TITLE
Get-GPPGroupMember returns Deserialize-GPPSectionGroups.ps1 errors in 0.3.0

### ISSUE THREAD

**Issue by Borgquite** [exchange12rocks/PSGPPreferences#34]
Having installed 0.3.0:

```
New-GPO "Test GPO"
$newmember = New-GPPGroupMember -Name "NETBIOSNAME\Domain Admins" -Action ADD
New-GPPGroup -GPOName "Test GPO" -Update -Name "Administrators" -Members $newmember
Get-GPPGroupMember -GPOName "Test GPO" -GroupName "Administrators" -Name "NETBIOSNAME\Domain Admins"
```

> Cannot find an overload for "new" and the argument count: "4".
> At C:\Program Files\WindowsPowerShell\Modules\PSGPPreferences\0.3.0\Serialization\Groups\Deserialize-GPPSectionGroups.ps1:57 char:17
> + ...             $GroupsMembers.Add([GPPItemGroup]::new($GPPItemProperties ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], MethodException
>     + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Same error also occurs if you run New-GPPGroup again after that:

`New-GPPGroup -GPOName "Test GPO" -Update -Name "Administrators" -Members $newmember`

> Cannot find an overload for "new" and the argument count: "4".
> At C:\Program Files\WindowsPowerShell\Modules\PSGPPreferences\0.3.0\Serialization\Groups\Deserialize-GPPSectionGroups.ps1:57 char:17
> + ...             $GroupsMembers.Add([GPPItemGroup]::new($GPPItemProperties ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], MethodException
>     + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Can you fix? :)

**Comment by exchange12rocks** [comment]
Oops, not all changes for #29 got into that commit 🤦‍♂️
I am sorry. Should be all right with v.0.3.1 - already in the gallery

**Comment by Borgquite** [comment]
Seems to be working :)
